taco:
  orders:
    pageSize: 10

spring:
  jpa:
    show-sql: true
    
# Activating profile    
#  profiles:
#    active:
#    - prod

#logging:
#  level:
#    tacos: DEBUG   

# Start profile section ---
---                 
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql:/localhost/tacocloud
    username: tacouser
    password: tacopassword
        
logging:
  level:
    tacos: WARN   
        
#  security:
#    user:
#      name: buzz
#      password: infinity

#logging:
#  path: /var/logs
#  file: TacoCloud.log
#  level:
#    root: WARN
#    org.springframework.security: DEBUG
    
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacouser
#    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
#    schema:
#    - order-schema.sql
#    - ingredient-schema.sql
#    - taco-schema.sql
#    - user-schema.sql
#    data:
#    - ingredients.sql
#    jndi-name: java:/comp/env/jdbc/tacoCloudDS
    
# 5.1.3 - Configuring the embedded server
#server:
#  port: 0